/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Peternakan.GUI;

import Peternakan.tools.DBConnection;
import javax.swing.table.DefaultTableModel;
import javax.swing.ComboBoxModel;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Administrator
 */
public class PerawatanGUI extends javax.swing.JFrame {

    /**
     * Creates new form PerawatanGUI
     */
    DefaultTableModel tblmodel;
    Connection conn;
    
    public PerawatanGUI() {
        initComponents();
        DBConnection openconn = new DBConnection();
        this.conn = openconn.create_connection();
        this.tblmodel = (DefaultTableModel)tbl_perawatan.getModel();
        this.load_data();
    }
    
    public void reset_table(){
        int rowCount = this.tbl_perawatan.getRowCount();
        for(int i = rowCount - 1; i >= 0; i--){
            this.tblmodel.removeRow(i);
        }
    }
    
    public void reset_cmb(){
        this.cmb_petani.removeAllItems();
        this.cmb_hewan.removeAllItems();
        this.cmb_pakan.removeAllItems();
    }
    
    public void load_data() {
        try{
            String select_table_sql = "SELECT *FROM PERAWATAN";
            Statement statement_table = this.conn.createStatement();
            ResultSet result_table = statement_table.executeQuery(select_table_sql);
            
            this.reset_table();
            
            while (result_table.next()){
                String idPerawatan = result_table.getString(1);
                String idPetani = result_table.getString(4);
                String idHewan = result_table.getString(2);
                String idPakan = result_table.getString(3);
                String tanggalPerawatan = result_table.getString(5);
                String dataMenu[] = {idPerawatan,idPetani,idHewan,idPakan,tanggalPerawatan};
                
                this.tblmodel.addRow(dataMenu);
            }
            String select_cmb_pakan_sql = "SELECT *FROM PAKAN";
            Statement statement_cmb_pakan = this.conn.createStatement();
            ResultSet result_cmb_pakan = statement_cmb_pakan.executeQuery(select_cmb_pakan_sql);
            
            String select_cmb_hewan_sql = "SELECT *FROM HEWAN";
            Statement statement_cmb_hewan = this.conn.createStatement();
            ResultSet result_cmb_hewan = statement_cmb_hewan.executeQuery(select_cmb_hewan_sql);
            
            String select_cmb_petani_sql = "SELECT *FROM PETANI";
            Statement statement_cmb_petani = this.conn.createStatement();
            ResultSet result_cmb_petani = statement_cmb_petani.executeQuery(select_cmb_petani_sql);
            
            this.reset_cmb();
            
            while(result_cmb_pakan.next()){
                String idPakan = result_cmb_pakan.getString(1);
                String data = idPakan;
                this.cmb_pakan.addItem(data);
            }
            
            while(result_cmb_petani.next()){
                String idPetani = result_cmb_petani.getString(1);
                String data = idPetani;
                this.cmb_petani.addItem(data);
            }
            
            while(result_cmb_hewan.next()){
                String idHewan = result_cmb_hewan.getString(1);
                String data = idHewan;
                this.cmb_hewan.addItem(data);
            }
            
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_perawatan = new javax.swing.JTable();
        cmb_petani = new javax.swing.JComboBox<>();
        cmb_hewan = new javax.swing.JComboBox<>();
        txt_treatDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        cmb_pakan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        btn_change = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nama_petani = new javax.swing.JTextField();
        txt_jenis_hewan = new javax.swing.JTextField();
        txt_tipe_pakan = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_perawatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Perawatan", "ID Petani", "ID Hewan", "ID Pakan", "Tanggal Perawatan"
            }
        ));
        tbl_perawatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_perawatanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_perawatan);

        cmb_petani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_petani.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_petaniItemStateChanged(evt);
            }
        });

        cmb_hewan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_hewan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_hewanItemStateChanged(evt);
            }
        });

        txt_treatDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_treatDateActionPerformed(evt);
            }
        });

        jLabel2.setText("Tanggal Perawatan");

        jLabel3.setText("Petani");

        jLabel4.setText("Hewan");

        btn_save.setText("Simpan");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        cmb_pakan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_pakan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_pakanItemStateChanged(evt);
            }
        });
        cmb_pakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_pakanActionPerformed(evt);
            }
        });

        jLabel1.setText("Pakan");

        btn_delete.setText("Hapus");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        btn_change.setText("Ubah");
        btn_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeActionPerformed(evt);
            }
        });

        jLabel5.setText("Perawatan");

        jLabel7.setText("(YYY-MM-DD)");

        txt_nama_petani.setEditable(false);

        txt_jenis_hewan.setEditable(false);

        txt_tipe_pakan.setEditable(false);

        jMenu1.setText("Menu");

        MenuItem.setText("Pakan");
        MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_treatDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmb_pakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tipe_pakan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(282, 282, 282))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_save)
                .addGap(369, 369, 369))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmb_petani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nama_petani, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmb_hewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_jenis_hewan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_change, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_petani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_nama_petani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_hewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete)
                    .addComponent(btn_change)
                    .addComponent(txt_jenis_hewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_pakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txt_tipe_pakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_treatDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_treatDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_treatDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_treatDateActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO PERAWATAN(ID_H,id_pa,id_pe,tanggal_perawatan) values(?,?,?,?)";
            String id_hewan = this.cmb_hewan.getSelectedItem().toString();
            String id_pakan = this.cmb_pakan.getSelectedItem().toString();
            String id_petani = this.cmb_petani.getSelectedItem().toString();
            String tanggal_perawatan = this.txt_treatDate.getText();
            
            
            System.out.print(id_hewan);
            
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, id_hewan);
            statement.setString(2, id_pakan);
            statement.setString(3, id_petani);
            statement.setString(4, tanggal_perawatan);
            
            int rows = statement.executeUpdate();
            if (rows > 0) {
                this.load_data();
                JOptionPane.showMessageDialog(this, "Perawatan Tanggal " + txt_treatDate.getText() + " Tersimpan");
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        try{
            String id = this.txt_id.getText();
            String sql = "DELETE FROM PERAWATAN WHERE ID_PER = ?";
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, id);
            
            int rows = statement.executeUpdate();
            if (rows > 0) {
                this.load_data();
                JOptionPane.showMessageDialog(this, "Menu " + txt_id.getText() + " Terhapus");
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeActionPerformed
        // TODO add your handling code here:
        try{
            String id = this.txt_id.getText();
            
            String tanggal_perawatan = this.txt_treatDate.getText();
            String id_h = this.cmb_hewan.getSelectedItem().toString();
            String id_pa = this.cmb_pakan.getSelectedItem().toString();
            String id_pe = this.cmb_petani.getSelectedItem().toString();
            String sql = "UPDATE PERAWATAN SET TANGGAL_PERAWATAN = ?, id_h = ?, id_pa = ?, id_pe = ? WHERE ID_PER = ?";
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, tanggal_perawatan);
            statement.setString(2, id_h);
            statement.setString(3, id_pa);
            statement.setString(4, id_pe);
            statement.setString(5, id);
            
            int rows = statement.executeUpdate();
            if (rows > 0) {
                this.load_data();
                JOptionPane.showMessageDialog(this, "Menu " + txt_treatDate.getText() + " Terganti");
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_changeActionPerformed

    private void MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActionPerformed
        // TODO add your handling code here:
        new PakanGUI().setVisible(true);
    }//GEN-LAST:event_MenuItemActionPerformed

    private void tbl_perawatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_perawatanMouseClicked
        // TODO add your handling code here:
            int row = tbl_perawatan.getSelectedRow();
            String petani = this.tblmodel.getValueAt(row, 1).toString();
            String hewan = this.tblmodel.getValueAt(row, 2).toString();
            String pakan = this.tblmodel.getValueAt(row, 3).toString();
            String tanggal_perawatan = this.tblmodel.getValueAt(row, 4).toString();
            String id_perawatan = this.tblmodel.getValueAt(row, 0).toString();
            
            DefaultComboBoxModel model_petani = (DefaultComboBoxModel) this.cmb_petani.getModel();
            JComboBox petani_cmb = new JComboBox(model_petani);
            DefaultComboBoxModel model_hewan = (DefaultComboBoxModel) this.cmb_hewan.getModel();
            JComboBox hewan_cmb = new JComboBox(model_hewan);
            DefaultComboBoxModel model_pakan = (DefaultComboBoxModel) this.cmb_pakan.getModel();
            JComboBox pakan_cmb = new JComboBox(model_pakan);
            
            petani_cmb.setSelectedItem(petani);
            hewan_cmb.setSelectedItem(hewan);
            pakan_cmb.setSelectedItem(pakan);
            
           
            this.txt_id.setText(id_perawatan);
            this.txt_treatDate.setText(tanggal_perawatan);
            
            
            
    }//GEN-LAST:event_tbl_perawatanMouseClicked

    private void cmb_petaniItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_petaniItemStateChanged
        // TODO add your handling code here:
        if(this.cmb_petani.getSelectedItem() != null){
            int id_petani = Integer.valueOf(this.cmb_petani.getSelectedItem().toString());
            String sql_pakan = "select nama_pe from petani where id_pe = '"+id_petani+"'";
            try{
            Statement statement_pakan = conn.createStatement();
            ResultSet result = statement_pakan.executeQuery(sql_pakan);
            while(result.next()){
                String nama_petani = result.getString(1);
                this.txt_nama_petani.setText(nama_petani);
            }
            
        }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
        
        
    }//GEN-LAST:event_cmb_petaniItemStateChanged
    
    private void cmb_pakanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_pakanItemStateChanged
        // TODO add your handling code here:
        if(this.cmb_pakan.getSelectedItem() != null){
            int id_pakan = Integer.valueOf(this.cmb_pakan.getSelectedItem().toString());
            String sql_pakan = "select tipe_pa from pakan where id_pa = '"+id_pakan+"'";
            try{
            Statement statement_pakan = conn.createStatement();
            ResultSet result = statement_pakan.executeQuery(sql_pakan);
            while(result.next()){
                String tipe_pakan = result.getString(1);
                this.txt_tipe_pakan.setText(tipe_pakan);
            }
            
        }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
        
        
        

    }//GEN-LAST:event_cmb_pakanItemStateChanged

    private void cmb_pakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_pakanActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cmb_pakanActionPerformed

    private void cmb_hewanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_hewanItemStateChanged
        // TODO add your handling code here:
        if(this.cmb_hewan.getSelectedItem() != null){
            int id_hewan = Integer.valueOf(this.cmb_hewan.getSelectedItem().toString());
            String sql_pakan = "select jenis_h from hewan where id_h = '"+id_hewan+"'";
            try{
            Statement statement_pakan = conn.createStatement();
            ResultSet result = statement_pakan.executeQuery(sql_pakan);
            while(result.next()){
                String jenis_hewan = result.getString(1);
                this.txt_jenis_hewan.setText(jenis_hewan);
            }
            
        }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmb_hewanItemStateChanged

        
        
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItem;
    private javax.swing.JToggleButton btn_change;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmb_hewan;
    private javax.swing.JComboBox<String> cmb_pakan;
    private javax.swing.JComboBox<String> cmb_petani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_perawatan;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_jenis_hewan;
    private javax.swing.JTextField txt_nama_petani;
    private javax.swing.JTextField txt_tipe_pakan;
    private javax.swing.JTextField txt_treatDate;
    // End of variables declaration//GEN-END:variables
}
